### ISSUE TITLE
Feedback when no errors found

### ISSUE THREAD

**Issue by snomos** [divvun/divvun-gramcheck-web#9] opened 2020-03-02 14:18 UTC
There should be a feedback message telling the user that no errors where found, to clearly indicate that the processing is done (and the status of the outcome). As it is now, there's no visual feedback at all, and one could believe that it just is very slow.

**Comment by bbqsrc** [comment] 2020-03-18 11:26
Bug #11 was caused by this too. The user had disabled all error checking by accident, and then bam, nothing works. :)

**Comment by bbqsrc** [comment] 2020-03-18 12:52
The UI should show that no results were found, and if any error types are marked as ignored, suggest that the user might want to review their ignored grammar rules settings with a link.

**Comment by zoomix** [comment] 2023-11-15 15:50
![image](https://github.com/divvun/divvun-gramcheck-web/assets/813082/4b4502ad-bf4d-4f5f-a1d7-f7903a6bd60b)

![image](https://github.com/divvun/divvun-gramcheck-web/assets/813082/c2af3159-3906-4df8-968e-7824ac584bf0)

Solution examples.

**Closed** 2024-04-25 12:22 UTC
Labels: bug, support
